export const imageData = [
  {
    id: 1,
    src: "/images/deluxe-haven.jpeg",
    name: "Deluxe Haven",
    price: "#30,000",
    noOfOccupant: 1,
    roomCategory: "deluxe haven",
  },
  {
    id: 2,
    src: "/images/deluxe-haven2.jpeg",
    name: "Deluxe Haven",
    price: "#30,000",
    noOfOccupant: 1,
    roomCategory: "deluxe haven",
  },
  {
    id: 3,
    src: "/images/signature-stay.jpeg",
    name: "Signature Stay",
    price: "#50,000",
    noOfOccupant: 1,
    roomCategory: "signature stay",
  },
  {
    id: 4,
    src: "/images/signature-stay-2.jpeg",
    name: "Signature Stay",
    price: "#50,000",
    noOfOccupant: 1,
    roomCategory: "signature stay",
  },
  {
    id: 5,
    src: "/images/garden-retreat.jpeg",
    name: "Garden Retreat",
    price: "#60,000",
    noOfOccupant: 2,
    roomCategory: "garden retreat",
  },
  {
    id: 6,
    src: "/images/garden-retreat-2.jpeg",
    name: "Garden Retreat",
    price: "#60,000",
    noOfOccupant: 2,
    roomCategory: "garden retreat",
  },
  {
    id: 7,
    src: "/images/skyline-deluxe.jpg",
    name: "Skyline Deluxe",
    price: "#90,000",
    noOfOccupant: 2,
    roomCategory: "skyline deluxe",
  },
  {
    id: 8,
    src: "/images/skyline-deluxe-2.jpg",
    name: "Skyline Deluxe",
    price: "#90,000",
    noOfOccupant: 2,
    roomCategory: "skyline deluxe",
  },
  {
    id: 9,
    src: "/images/luxe-comfort.jpeg",
    name: "Luxe Comfort Room",
    price: "#120,000",
    noOfOccupant: 2,
    roomCategory: "luxe comfort room",
  },
  {
    id: 10,
    src: "/images/luxe-comfort-2.jpeg",
    name: "Luxe Comfort Room",
    price: "#120,000",
    noOfOccupant: 2,
    roomCategory: "luxe comfort room",
  },
];
