import {
  BedDouble,
  BedSingle,
  Tv,
  Wifi,
  AirVent,
  ShowerHead,
  Building,
  Refrigerator,
  ClipboardType,
  ConciergeBell,
  Flower,
  Coffee,
  Bath,
  Lamp,
  Mountain,
  CloudRain,
  GlassWater,
  Briefcase,
  Moon,
  Armchair,
  Key,
  Utensils,
  VolumeX,
  Shirt,
} from "lucide-react";

export const roomData = [
  {
    id: 1,
    src: "/images/deluxe-haven.jpeg",
    name: "Deluxe Haven",
    slug: "deluxe-haven",
    price: "#30,000",
    noOfOccupant: 1,
    roomCategory: "deluxe haven",
    peaks: [
      { name: "Queen bed", icon: <BedSingle /> },
      { name: "Smart TV", icon: <Tv /> },
      { name: "Free Wi-Fi", icon: <Wifi /> },
      { name: "Air condition", icon: <AirVent /> },
      { name: "Walk-in shower", icon: <ShowerHead /> },
    ],
  },
  {
    id: 2,
    src: "/images/deluxe-haven2.jpeg",
    name: "Deluxe Haven",
    slug: "deluxe-haven-2",
    price: "#30,000",
    noOfOccupant: 1,
    roomCategory: "deluxe haven",
    peaks: [
      { name: "Queen bed", icon: <BedSingle /> },
      { name: "Smart TV", icon: <Tv /> },
      { name: "Free Wi-Fi", icon: <Wifi /> },
      { name: "Air conditioning", icon: <AirVent /> },
      { name: "Walk-in shower", icon: <ShowerHead /> },
    ],
  },
  {
    id: 3,
    src: "/images/signature-stay.jpeg",
    name: "Signature Stay",
    slug: "signature-stay",
    price: "#50,000",
    noOfOccupant: 1,
    roomCategory: "signature stay",
    peaks: [
      { name: "King bed", icon: <BedDouble /> },
      { name: "City view", icon: <Building /> },
      { name: "Mini fridge", icon: <Refrigerator /> },
      { name: "Work desk", icon: <ClipboardType /> },
      { name: "Room service", icon: <ConciergeBell /> },
    ],
  },
  {
    id: 4,
    src: "/images/signature-stay-2.jpeg",
    name: "Signature Stay",
    slug: "signature-stay-2",
    price: "#50,000",
    noOfOccupant: 1,
    roomCategory: "signature stay",
    peaks: [
      { name: "King bed", icon: <BedDouble /> },
      { name: "City view", icon: <Building /> },
      { name: "Mini fridge", icon: <Refrigerator /> },
      { name: "Work desk", icon: <ClipboardType /> },
      { name: "Room service", icon: <ConciergeBell /> },
    ],
  },
  {
    id: 5,
    src: "/images/garden-retreat.jpeg",
    name: "Garden Retreat",
    slug: "garden-retreat",
    price: "#60,000",
    noOfOccupant: 2,
    roomCategory: "garden retreat",
    peaks: [
      { name: "Garden view", icon: <Flower /> },
      { name: "Private balcony", icon: <Coffee /> },
      { name: "Luxury bath", icon: <Bath /> },
      { name: "Tea corner", icon: <Coffee /> },
      { name: "Soft lighting", icon: <Lamp /> },
    ],
  },
  {
    id: 6,
    src: "/images/garden-retreat-2.jpeg",
    name: "Garden Retreat",
    slug: "garden-retreat-2",
    price: "#60,000",
    noOfOccupant: 2,
    roomCategory: "garden retreat",
    peaks: [
      { name: "Garden view", icon: <Flower /> },
      { name: "Private balcony", icon: <Coffee /> },
      { name: "Luxury bath", icon: <Bath /> },
      { name: "Tea corner", icon: <Coffee /> },
      { name: "Soft lighting", icon: <Lamp /> },
    ],
  },
  {
    id: 7,
    src: "/images/skyline-deluxe.jpg",
    name: "Skyline Deluxe",
    slug: "skyline-deluxe",
    price: "#90,000",
    noOfOccupant: 2,
    roomCategory: "skyline deluxe",
    peaks: [
      { name: "Skyline view", icon: <Mountain /> },
      { name: "Rain shower", icon: <CloudRain /> },
      { name: "Mini bar", icon: <GlassWater /> },
      { name: "Executive desk", icon: <Briefcase /> },
      { name: "Evening turndown", icon: <Moon /> },
    ],
  },
  {
    id: 8,
    src: "/images/skyline-deluxe-2.jpg",
    name: "Skyline Deluxe",
    slug: "skyline-deluxe-2",
    price: "#90,000",
    noOfOccupant: 2,
    roomCategory: "skyline deluxe",
    peaks: [
      { name: "Skyline view", icon: <Mountain /> },
      { name: "Rain shower", icon: <CloudRain /> },
      { name: "Mini bar", icon: <GlassWater /> },
      { name: "Executive desk", icon: <Briefcase /> },
      { name: "Evening turndown", icon: <Moon /> },
    ],
  },
  {
    id: 9,
    src: "/images/luxe-comfort.jpeg",
    name: "Luxe Comfort Room",
    slug: "luxe-comfort-room",
    price: "#120,000",
    noOfOccupant: 2,
    roomCategory: "luxe comfort room",
    peaks: [
      { name: "King bed", icon: <BedDouble /> },
      { name: "Spacious lounge", icon: <Armchair /> },
      { name: "Rooftop access", icon: <Key /> },
      { name: "In-room dining", icon: <Utensils /> },
      { name: "Soundproof walls", icon: <VolumeX /> },
      { name: "Luxury bathrobe", icon: <Shirt /> },
    ],
  },
  {
    id: 10,
    src: "/images/luxe-comfort-2.jpeg",
    name: "Luxe Comfort Room",
    slug: "luxe-comfort-room-2",
    price: "#120,000",
    noOfOccupant: 2,
    roomCategory: "luxe comfort room",
    peaks: [
      { name: "King bed", icon: <BedDouble /> },
      { name: "Spacious lounge", icon: <Armchair /> },
      { name: "Rooftop access", icon: <Key /> },
      { name: "In-room dining", icon: <Utensils /> },
      { name: "Soundproof walls", icon: <VolumeX /> },
      { name: "Luxury bathrobe", icon: <Shirt /> },
    ],
  },
];

export const facilitiesData = [
  {
    id: 1,
    name: "Indoor Gym",
    src: "/images/gym-interior.jpeg",
    description:
      "Stay active during your stay with our fully equipped fitness center. From cardio machines to free weights and yoga mats, our gym has everything you need to keep up with your routine in a comfortable, modern space.",
    category: "Gym",
  },
  {
    id: 2,
    name: "Lobby",
    src: "/images/lobby.jpg",
    description:
      "The heart of the hotel. Our lobby isn’t just a waiting area — it’s your first impression of comfort and elegance. Spacious, welcoming, and staffed with attentive professionals ready to assist you, it sets the tone for your entire stay..",
    category: "hotel lobby",
  },
  {
    id: 3,
    name: "The Restaurant",
    src: "/images/restaurant.jpeg",
    description:
      "More than just meals — it’s an experience. Our restaurant offers a curated menu of local and international cuisine, prepared with fresh ingredients and served in a warm, welcoming setting. From breakfast buffets to fine dining dinners, we’ve got your cravings covered",
    category: "restaurant",
  },
  {
    id: 4,
    name: "Lounge Bar",
    src: "/images/lounge-bar.jpg",
    description:
      "The perfect spot to unwind. Sip on handcrafted cocktails, premium wines, or your favorite spirits in a stylish lounge atmosphere — whether you’re celebrating, socializing, or simply relaxing after a long day.",
    category: "lounge",
  },
  {
    id: 5,
    name: "Event Hall & Conference",
    src: "/images/hall.jpg",
    description:
      "A stage for unforgettable moments. From weddings to galas, our event hall combines elegant design with customizable layouts to suit any occasion. Backed by professional planning support, modern sound systems, and seamless service, we make sure your event runs flawlessly while leaving a lasting impression on every guest.",
    category: "banquet hall",
  },
  {
    id: 6,
    name: "Meeting Room",
    src: "/images/meeting-room.jpg",
    description:
      "Where business meets focus. Equipped with high-speed connectivity, presentation tools, and flexible seating, our meeting rooms are built to help ideas flow and decisions get made.",
    category: "meeting room",
  },
  {
    id: 7,
    name: "Swimming Pool",
    src: "/images/swimming-pool.jpg",
    description:
      "Not just a pool — an escape. Whether you’re starting your morning with energizing laps or unwinding under the sun with a cocktail, our poolside area is designed for relaxation and leisure. Comfortable loungers, clean facilities, and a serene atmosphere make it the perfect spot to disconnect and recharge.",
    category: "swimming pool",
  },
  {
    id: 8,
    name: "Spa",
    src: "/images/spa.jpeg",
    description:
      "Your escape into relaxation. Indulge in massages, facials, or full-body treatments designed to melt away stress and rejuvenate your body and mind.",
    category: "spa",
  },
];
